AWSTemplateFormatVersion: "2010-09-09"
Description: S3 cloudformation template storage-  for Practera Cloud Projects infrastructure

Metadata:
  Authors:
    Description: Based on AWS best practise.
  License:
    Description:
      Copyright 2022 Intersective PTY LTD and its affiliates. All Rights
      Reserved.

Parameters:
  CodeBuildName:
    Type: String
  Email:
    Type: String
  StackName:
    Default: pcloud
    Type: String
  Env:
    Description: Environment type.
    Default: dev
    Type: String
    ConstraintDescription: must specify dev,test,live.
  CodeCommitHTTPSUrl:
    Type: String

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${StackName}-${CodeBuildName}-${Env}"
      Description: My CodeBuild Project using CodeCommit
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODECOMMIT
        Location: !Ref CodeCommitHTTPSUrl
        GitCloneDepth: 1
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:7.0
        ComputeType: BUILD_GENERAL1_SMALL
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Email
          Value: !Ref Email
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 15
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub "log-group-${StackName}-${CodeBuildName}-${Env}"
          StreamName: !Sub "stream-${StackName}-${CodeBuildName}-${Env}"

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CodeBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:*
                Resource: "*"

Outputs:
  CodeBuildProjectName:
    Description: CodeBuild Project Name
    Value: !Ref CodeBuildProject
