AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Lambda functions

Parameters:
  S3ObjectUrl:
    Type: String
    Description: HTTPS URL of the .zip file containing the GetPost function code.
  StackName:
    Default: pcloud
    Type: String
  Env:
    Description: Environment type.
    Default: dev
    Type: String
    ConstraintDescription: must specify dev,test,live.
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the IAM role to be attached to the Lambda function.


Resources:
  GetPostFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pcloud-lessonsixs3-dev
        S3Key: deployment-packages/api.zip
      Handler: api.getPost
      Runtime: nodejs18.x
      Role: !Ref LambdaExecutionRoleArn

  CreatePostFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pcloud-lessonsixs3-dev
        S3Key: deployment-packages/api.zip
      Handler: api.createPost
      Runtime: nodejs18.x
      Role: !Ref LambdaExecutionRoleArn

  UpdatePostFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pcloud-lessonsixs3-dev
        S3Key: deployment-packages/api.zip
      Handler: api.updatePost
      Runtime: nodejs18.x
      Role: !Ref LambdaExecutionRoleArn

  DeletePostFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pcloud-lessonsixs3-dev
        S3Key: deployment-packages/api.zip
      Handler: api.deletePost
      Runtime: nodejs18.x
      Role: !Ref LambdaExecutionRoleArn

  GetAllPostsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pcloud-lessonsixs3-dev
        S3Key: deployment-packages/api.zip
      Handler: api.getAllPosts
      Runtime: nodejs18.x
      Role: !Ref LambdaExecutionRoleArn
